### ISSUE TITLE
Add symlink to user files for simplicity

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox-docker-unfs#14]
It would be really nice to add a symlink to `/data/var/db/unfs` in the root directory of storage components. This would simplify getting to them and having to document this path.

I'd suggest using `/app` as the symlink, just to follow the conventions used in code services.

**Example:**  
`scp local-file gonano@123.45.67.89:/app/network-dir/`

vs

`scp local-file gonano@123.45.67.89:/data/var/db/unfs/network-dir/`

**Comment by notxarb** [comment]
This is being taken care of with pull request #17
