### ISSUE TITLE
plan hook should return a user

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-docker-unfs#15]
Odin expects the plan hook to return both an array of `users` and one specific `user`. The `user` is used as the primary user for tunneling. Currently, only `users` are getting returned.

**Comment by jedgalbraith** [comment]
@notxarb Any updates on this? Showing the user/pass in the Odin dashboard depends on this.

**Comment by notxarb** [comment]
fixed: https://github.com/nanobox-io/nanobox-hooks-unfs/pull/10

**Comment by jedgalbraith** [comment]
Looks great. Thanks.
